version: '3.8'

services:
  order-service:
    build: ./order-service
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://projeto-final-db.c87oyyuuqyrd.us-east-1.rds.amazonaws.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=passwordSuperSegura123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SERVER_PORT=8083
      - SERVER_ADDRESS=0.0.0.0

  product-service:
    build: ./product-service
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://projeto-final-db.c87oyyuuqyrd.us-east-1.rds.amazonaws.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=passwordSuperSegura123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SERVER_PORT=8082
      - SERVER_ADDRESS=0.0.0.0

  user-service:
    build: ./user-service
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://projeto-final-db.c87oyyuuqyrd.us-east-1.rds.amazonaws.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=passwordSuperSegura123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SERVER_PORT=8081
      - SERVER_ADDRESS=0.0.0.0
      - LOGGING_LEVEL_ROOT=DEBUG

  api-gateway:
    build: ./api-gateway
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - user-service
      - product-service
      - order-service